### ISSUE TITLE
Ncurses console subscriber

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#2]
Build a console for bolo, using ncurses, that can provide an htop-style heads up display for seeing states and metrics.

**Comment by GrayTShirt** [comment]
Interesting, you could use UTF8 braille for graphs... https://github.com/mydzor/bash-drawille

**Comment by filefrog** [comment]
Yeah, I've been looking for some sort of unicode code points for the time series data, a la sparklines

**Comment by filefrog** [comment]
http://rosettacode.org/wiki/Sparkline_in_unicode is better.

9 bins (0-8) instead of the 5 that braille gets us, at the expense of showing half the number of datapoints (which I'm okay with).  Plus, it eliminates the spacing issue seen with braille dots.

**Comment by jhunt** [comment]
Here's what bolo2console spits out currently under `./spin`:

```
EVENT 1463705151 subsys=sudo,user=root,host=box sudo: root logged in (maybe...)
EVENT 1463705157 subsys=sudo,user=root,host=box sudo: root logged in (maybe...)
SAMPLE 1463705100 t=sample,mode=dev 10 4.530000e+02 3.126900e+04 1.425510e+05 1.425510e+04 9.173866e+07
EVENT 1463705163 subsys=sudo,user=root,host=box sudo: root logged in (maybe...)
EVENT 1463705169 subsys=sudo,user=root,host=box sudo: root logged in (maybe...)
```

This is useful behavior, and I don't *think* it exists anywhere else, so I'm inclined to rename `bolo2console` to `bolo tail` and rebuild `bolo2console` as a curses app.

**Comment by jhunt** [comment]
(also, as an aside, should probably revisit bolo2log, since its output is less than awesome)

**Comment by jhunt** [comment]
<img width="346" alt="screen shot 2016-05-19 at 8 53 36 pm" src="https://cloud.githubusercontent.com/assets/20047/15413978/cc35df56-1e03-11e6-9232-179870c99e3a.png">

**Comment by jhunt** [comment]
<img width="701" alt="screen shot 2016-05-21 at 2 23 06 pm" src="https://cloud.githubusercontent.com/assets/20047/15450891/9094fb32-1f5f-11e6-9160-65af90a5539d.png">

**Comment by jhunt** [comment]
Initial (serviceable) implementation done.  Probably needs color and some other accoutrements, but I'd rather use it for a while in prod before committing to one behavior or another.
