### ISSUE TITLE
New bolo2influxdb subscriber

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#25]
Push metrics into an InfluxDB backend

**Comment by filefrog** [comment]
Here's a BOSH release to get started on deployment quickly: https://github.com/shinji62/influxdb-boshrelease

**Comment by GrayTShirt** [comment]
would it make sense to add ZMQ listener support to influxdb?

**Comment by GrayTShirt** [comment]
I did some more research, the prometheus.io guys didn't think it was a viable storage backend
https://docs.google.com/document/d/1OgnI7YBCT_Ub9Em39dEfx9BuiqRNS3oA62i8fJbwwQ8/edit#heading=h.e32xcwnzxp3e

I'm not sure if they did the benchmark completely wrong but as it stands this should probably be investigated further before influx is to be used.

**Comment by filefrog** [comment]
Bolo is more a toolkit, than a fully integrated product.  I'd rather support the popular time series DBs and visualization packages, no matter what other monitoring systems want to use.

**Comment by filefrog** [comment]
Looks like this is going to be pretty easier, since the protocol is line-based and works over UDP

**Comment by GrayTShirt** [comment]
influxdb supports multiple protocols include, collectd, opentsdb, and graphite. It might make sense to use one of those protocols, and knock out two birds with one stone.

**Comment by geofffranks** [comment]
@GrayTShirt i'm in the middle of writing something to stream bolo data to influxdb. Is this something you're actively working on as well?

**Comment by geofffranks** [comment]
See https://github.com/bolo/bolo2influxdb for the work in progress of a bolo-to-influxdb event stream
