### ISSUE TITLE
Move to Redis for Key Storage

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#30]
Document Redis setup, including how to look up keys.

Then, drop the key management from the ZMQ protocol and the stat_bolo client

**Comment by GrayTShirt** [comment]
I found that using postgresql as a STATE backend / state-machine incurs a high degree of latency in the system, what do you think about pushing state and transitions directly from core into redis?

**Comment by filefrog** [comment]
For the scope of this ticket, let's just stick to Keys.

I'm not sure how Redis would handle History.

**Comment by GrayTShirt** [comment]
I was thinking that history would remain in postgres

**Comment by filefrog** [comment]
So have STATE data in both systems?

**Comment by GrayTShirt** [comment]
effectively, postgres being a full history log, and redis being current state (IE: since last transition)

**Comment by GrayTShirt** [comment]
so key broadcasting would be dropped, but the agent could still submit keys?
