### ISSUE TITLE
Update rpm spec to package redis subscriber

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#35]

**Comment by filefrog** [comment]
I would rather figure out how to build test rpms / debs via Travis and host release pkgs somewhere on the internet,  for a longer-term fix.

Thoughts?

**Comment by filefrog** [comment]
I put in #36 to build a better release process.  This ticket can continue down the path of putting the redis subscriber into the RPM explicitly, and that issue will track efforts to build a release process.
