### ISSUE TITLE
Better Release Process

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#36]
Build a better release process that results in:

- RPMs for each released version
- DPKG files for each released version
- Detailed Release Notes
- Version bumps
- git tags
- Distribution tarballs

Ideally, this would be as scripted and automated as possible, woth clean room build envs. Maybe travs-ci can help? Otherwise, we can try to use concourse ci (which is a bit more involved, but definitely does what is needed)

**Comment by filefrog** [comment]
I think we can (legitimately) use docker for this.  I'm going to investigate setting up docker containers to build RPM and DPKG packages.

Should also look into https://packagecloud.io/ for the hosting part.  They have a Travis integration.  Combined with a Docker build environment, I think you get all of the automation / clean-room / hosting, with little hassle.

**Comment by filefrog** [comment]
Almost done building dependencies (under a new, soon-to-be-pushed project called `bolo/deps`), for Debian/Ubumtu systems via debuild.  RPMs should be right on the heels of that.

**Comment by filefrog** [comment]
Dep builds are done.  Just need to add the necessary installation instructions to README for the packagecloud piece and we're good.

**Comment by filefrog** [comment]
The Docker portion of this is done, and documented per #45
