### ISSUE TITLE
Bolo Forwarder

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#4]
Do some research into a forwarder architecture that would allow multiple bolos to forward their state/metric/event data to one or more consolidation hubs.  This can be used for geographically isolated data centers to consolidate across WAN links, or to help a site merge data from lots of BOSH deployments into one visualization point.

Need to figure out:
1. What would be different in the forwarding protocol from the current broadcast protocol
2. How much compression can we achieve given reasonable collection and aggregation intervals, and a reasonable number of bolo subscribers hanging off of multiple bolos across WAN links
3. How much does this change complicate the architecture

**Comment by GrayTShirt** [comment]
I view this as giant broadcast to broadcast router. I still think we should check for freshness, though.
