### ISSUE TITLE
bolo2rrd - enhancement mega ticket

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#46]
- [ ] Custom rrd ping times based on 3-5x the window size
- [ ] mmap rrd map
- [ ] add window length to rrd map
- [x] add metric type to rrd map
- [x] fix stat of rrd abs path to check the cache daemon first, then fall back to the path for CREATE logic.

**Comment by jhunt** [comment]
@GrayTShirt I reformatted the issue description to be a list of checkable items, and then checked off the ones I think are done.

Do we still want / need the rest?

**Comment by GrayTShirt** [comment]
This is good. Thanks!

**Comment by jhunt** [comment]
Are we still interested in `mmap()`'ing the rrd map?

Do we still need to store window sizes in the rrd map?

I'm totally cool with the heartbeat / step times based on reported window (although that will only be possible on create)

**Comment by GrayTShirt** [comment]
We probably don't need to mmap the mapping-file. But, It might make more sense to append the mapping-file upon rrd creation.

window sizes would be useful for an HTTP api endpoint. Especially to convert from a per minute to per second RATES.

**Comment by jhunt** [comment]
Wouldn't an HTTP endpoint be better off hitting something like `bolo2pg`?

I'm going to implement the custom heartbeats into `rradefs()`, and then close this ticket.

**Comment by GrayTShirt** [comment]
the endpoint would be specific for getting timeseries data as json to be used in browser generated graphs.

**Comment by jhunt** [comment]
Also, I am apparently conflating projects.  TSDP broadcasts the window; bolo 0.x does not.
