### ISSUE TITLE
bolo2rrd does not use rrcached

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#49]
the daemon function in libvigor cleans the environment after the RRDCACHED_ADDRESS variable is set, thus the cache daemon is never used. 

verified /proc/<pid of bolo2rrd>/environ

I finally saw this behavior after zeroing in on the rrdcached statistics, (regex matching the full executable path) and saw a huge drop in IO, turns out I was matching bolo2rrd and rrdcached.

**Comment by GrayTShirt** [comment]
so this is still not working

**Comment by GrayTShirt** [comment]
I get the feeling that rrd_update_r doesn't support the environment variable

**Comment by filefrog** [comment]
Did you compile librrd with the rrdcached support?

**Comment by GrayTShirt** [comment]
rrdcached is installed on the machine so, maybe... I didn't compile this package

**Comment by filefrog** [comment]
run strings on librrd and see if it references the env var.  Alternatively, you could run bolo2rrd under strace and see if anybody every calls `getenv`

**Comment by GrayTShirt** [comment]
RRDCACHED_ADDRESS is referenced in the lib...

**Comment by GrayTShirt** [comment]
after looking at rrd_update.c in rrdtool, I'm starting to get the feeling we need to call a different function that rrd_update_r

**Comment by filefrog** [comment]
Blergh.  Sadly, that is a hard thing to test without spinning rrdcached.  Work up a patch and send it my way.

**Comment by GrayTShirt** [comment]
So I wanted so betweeen the rrdtool changes and the bolo2rrd changes this is working awesome! I went from a cpu io wait of 14% down to 3%.

**Comment by filefrog** [comment]
Sweet.  Can we close this?

**Comment by GrayTShirt** [comment]
Yes, I think we can. PR has been merged upstream. So, I think we're good.
