### ISSUE TITLE
Bolo Heartbeats

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#5]
Implement heartbeating between dbolo and bolo aggregator/forwarder. This will be used to keep the agent push socket open instead of re-initializing it every 7 seconds.

Heartbeating should work the following way:
A PUB endpoint (BEACON endpoint is created on the Core/Forwarder) and it publishes BEACON PDUs that have the time (interval) of the next BEACON message. The agent only attempts a reconnect after the hb_t session times out.

Heartbeating should be optional, and total agent reconnects should configurable.

Configurable options
- BEACON endpoint
- BEACON interval publishing
- Agent reconnects
- Agent heartbeat freshness

**Comment by filefrog** [comment]
Hey Dan, I assigned this to you since I believe you are already in the middle of the implementation.

Also, you can self-assign issues now!  Hooray!

**Comment by GrayTShirt** [comment]
Neat, and yes I am working on this, landed up scrapping all the REQ-REP work I had been doing.

**Comment by filefrog** [comment]
Merged
