### ISSUE TITLE
Memory leak in redis subscriber

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#52]
the redis reply object needs to be freed, I will be submitting a PR momentarily.

**Comment by filefrog** [comment]
For future reference, you don't have to create an issue if you're going to submit a PR.

**Comment by GrayTShirt** [comment]
oh, sorry, I guess I've been in the corporate world too long :(

**Comment by filefrog** [comment]
no worries. But Github uses a unified namespace for issue / PR numbering, so you end up burning two numbers - one for the issue and one for the PR.

**Comment by GrayTShirt** [comment]
oh, hmmm, that makes sense
