### ISSUE TITLE
Support EVENTS in PG subscriber

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#58]
The pg sub should capture events and store them in a seperate table.

**Comment by GrayTShirt** [comment]
should this be a new insterter type thread? or should we shim into reconcile and the existing insertion thread?

**Comment by GrayTShirt** [comment]
I think the second thing that needs to happen, is the aggregator needs to support ALERTS that don't have freshness, I'm thinking freshness value of 0 or -1.

**Comment by jhunt** [comment]
Did you ever make a PR against bolo/rfc to introduce the ALERT type?

**Comment by GrayTShirt** [comment]
I had started work on a PR, but upon implementation I felt I was duplicating effort that was made to extend to the cases I wanted to cover, (snmp traps AND cron scripts)

```
4.3.2.5  STATE

4.3.2.5.1  Data Frames

      1 (string/*)    Qualified name of the state
      1 (tstamp/8)    Time of state check
      1 (uint/4)      Check interval (in milliseconds)
      ? (string/*)    Summary message text

   If the check interval is 0, the check is not regular and should not
   be considered for freshness threshold violations.
```

**Comment by jhunt** [comment]
Closing this.  Feel free to re-visit with a PR.
