### ISSUE TITLE
memory leak in bolo2rrd

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#65]
given the data I've collected, I believe it's in the creator code

**Comment by GrayTShirt** [comment]
so I noticed when I set /usr/lib/bolo/bolo2rrd/rra.def then the memory leak is triggered

**Comment by jhunt** [comment]
How big is the memory leak?  Proportional to the number of new RRD files created?

> On Mar 24, 2016, at 9:23 AM, Dan Molik <notifications@github.com> wrote:
> 
> so I noticed when I set /usr/lib/bolo/bolo2rrd/rra.def then the memory leak is triggered
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

---
jrh

**Comment by GrayTShirt** [comment]
yes it does seem proportional

**Comment by jhunt** [comment]
Any additional research / findings on this?

**Comment by GrayTShirt** [comment]
not yet, I independently verified the accuracy of the core RATES, the good news is that it's accurate, but sometimes data is dropped, but given the hardware I'm running on, I'm not concerned.

**Comment by GrayTShirt** [comment]
Ok, I've been re-running with a defined rra file, It seems there was a misspelling in it, which would explain the high number of errors I was getting.

**Comment by jhunt** [comment]
So is this still an issue / do you have memory usage graphs (#someta) to back it up?

**Comment by GrayTShirt** [comment]
No it's not the same bug I though it was. 
The problem is, that if the RRD fails to create (bad rra definition) the daemon tries to create it in the next window. Thus, we start generating lots of errors. and we eventually back up either the cache daemon or ourselves.

So I would call this user error. We could validate the rra definition?

**Comment by jhunt** [comment]
Or, we could do what I did for the BOSH release and just migrate that logic down.  TL;DR: BOSH release users just specify the granularity and the retention and we figure out the RRA for them:

https://github.com/cloudfoundry-community/bolo-boshrelease/blob/master/jobs/rrd/templates/config/rradefs

So a user does something like this in their deployment manifest:

```
properties:
  bolo:
    rrd:
      retention:
        - { at: 1m, for: 5d }
        - { at: 5m, for: 21d }
        - { at: 1h, for: 180d }
        # etc.
```

And we figure out the rows, pdp, etc.

**Comment by GrayTShirt** [comment]
ok I'm happy with the outcome of this ticket.
