### ISSUE TITLE
Please clarify why we are multiplying by span in the rate_calc

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#69]
I'm not sure why we are multiplying by span here, it would be helpful if you could explain why we are.
Dimensional analysis would suggest when we divide by the time difference then multiple by the window span we no longer have a value/time (ie: bits/s) we just have bits, 
https://github.com/bolo/bolo/blob/master/src/data.c#L87

I also looked at the rrd subscriber code and we send the window size but we don't use it... what was the intention?

**Comment by jhunt** [comment]
Remember that RATE attempts to derive a rate-of-change per unit time, based on an increasing value that is reported irregularly throughout the window (i.e it is derived without the cooperation of the submitting system).

Consider the following timeline of events, with a 60s window:

- **t+0** - rate_reset is called.  `first = last = first_seen = last_seen = 0`
- **t+4** - value 13 is submitted.  `first = 13`, `first_seen = last_seen = t4`
- **t+24** - value 15 is submitted.  `last = 15`, `last_seen = t+34`
- **t+44** - value 17 is submitted.  `last = 17`, `last_seen = t+44`
- **t+60** - broadcast triggers, and RATE is calculated.

At **t+60**, the aggregator has a few ways of calculating the rate of change.

The naïve approach is `(last - first) / window`, which in this case would be `(17 - 13) / 60 = 4 / 60 = 15`

15 things a minute.

The _correct_ approach is to take into account when the first and last values were actually seen, and calculate the actual rate of change, and then project that onto the desired unit time.  That is `(last - first) / (last_seen - first_seen) * window`, or `(17 - 13) / ((t+44) - (t+4)) * 60`.  That translates (roughly) into English as  "we saw a net increase of 4 (13 -> 17) in space of 40 seconds, which equates to 1 every 10 seconds, extrapolated out to 6 every minute.

6 things a minute.

Now, anecdotally, If I told you that (as in this example) a value bumped by 2 every 20 seconds, would you calculate the rate as 15 things a minute?  Or does that sound more like 6 things a minute?

The tricky part is that the value may keep increasing every 20 seconds, but we may miss out on the packets.  If you drop any single value reported (either **t+4**, **t+24** or **t+44**), the implemented calculation stays the same.  The naïve calculation varies wildly in 2 out of the 3 possible scenarios.

**Comment by jhunt** [comment]
The window size being broadcast is directly in support of #46.  The thought being that subscribers may need to adjust there behavior based on the window size.  In RRD-land, the ping time and RRA density would need to be adjusted based on the window size.  If a metric is being reported hourly, it should have different heartbeat intervals and differently sized RRAs than a metric that gets reported minutely.  Esp. because monitoring system admins are usually held to calendar-based retention policies like "keep 13 months of metrics", not "keep the last X-thousand measurements or so"

**Comment by GrayTShirt** [comment]
Ok, so a window size of is the time length conversion from seconds to minutes, 5 minutes, etc.
That makes sense. 

and sounds like more work for #46 :)
