### ISSUE TITLE
Bolo Forget abnormalities

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#70]
I've been getting some weird behavior when using bolo-forget, it seems that some metrics become other metrics and sometimes the STATE isn't deleted correctly.

Is it possible the libvigor delete method is incorrect. like we just need to remove the link in the hash and point the previous node to the next free node?

**Comment by jhunt** [comment]
Yup.  There's definitely a bug, and it's a nasty one.  I'll get it fixed, and write some tests to catch regression.

**Comment by jhunt** [comment]
Try latest master (7efbc8f)
