### ISSUE TITLE
There is a rollover error in the core, dealing with RATE windowing

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#83]
I'm seeing huge, and implausible spikes on the order of PETA 10^(5*3)

**Comment by jhunt** [comment]
Care to elaborate?

**Comment by GrayTShirt** [comment]
The spikes seem to be single values, and occur more frequently on high traffic data sets. I have yet to see spike on SAMPLE data

**Comment by jhunt** [comment]
Have you been able to reproduce in a controlled environment?

**Comment by jhunt** [comment]
Closing this as it hasn't been reproduced.  Please re-open in the future, or submit a new issue / PR, with more detail on repro of issue.
