### ISSUE TITLE
opentsdb2bolo

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo#87]
I have some systems that currently can only submit data to OpenTSDB.  The protocol seems trivial enough:

```
put system.load.1m 1471535210 0.27 deployment=vault-warden index=1 job=vault
put system.cpu.user 1471535210 2.1 deployment=vault-warden index=1 job=vault
put system.cpu.sys 1471535210 2.2 deployment=vault-warden index=1 job=vault
put system.cpu.wait 1471535210 0.1 deployment=vault-warden index=1 job=vault
# etc.
```

I would like for the bolo aggregator to handle this submission format, either directly (via an OpenTSDB port, probably `13321`) or indirectly via some sort of input filter that listens for TSDB protocol submission, reformulates them as proper bolo PDUs and sends them to the aggregator.

The former solution seems easier, but the latter solution seems more in-line with the bolo "small components" philosophy we borrowed from UNIX.

**Comment by GrayTShirt** [comment]
Given the eventual upgrade to bolo-ng perhaps a standalone application
makes sense.

That being said I like the idea of different submitters and subscribers.
