### ISSUE TITLE
Implement "retries"

### ISSUE THREAD

**Issue by GrayTShirt** [bolo/bolo#89]
in the FSM (core aggregator) model a retry transition could be considered a:

OK -> CRIT -> CRIT only the second crit would execute a TRANSITION
and a
OK -> CRIT -> OK wouldn't even execute a TRANSITION event.

**Comment by jhunt** [comment]
How many retries would you support?

Would it be configurable?

If it's configurable, do we do it like we do freshness?

Ultimately, _retry_ is used as a policy tool to defer some action based on either a perceived false-positive behavior in the monitoring system ("oh, that goes away after 15 minutes, no worries") or as a way of state confirmation ("don't email me unless it's been down for 45 minutes") -- really that's two sides to the same coin.

The bolo design has always been to defer the policy to the edges (the subscribers) and try to keep it out of the core.

**Comment by GrayTShirt** [comment]
That makes sense.

Would you say that a subscriber is a more specialized FSM for transducing (https://en.wikipedia.org/wiki/Transducer) ? and the core is relegated to routing, and only has minimal historical awareness based out of necessity.

**Comment by jhunt** [comment]
I would characterize subscribers as policy and the bolo core as mechanism.

https://en.wikipedia.org/wiki/Separation_of_mechanism_and_policy
